# Generated by Django 2.2.7 on 2020-06-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetURL', models.CharField(max_length=100)),
                ('hash', models.CharField(blank=True, max_length=15, null=True)),
                ('shrinkedURL', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
